class PlantData {
  static const Map<String, List<String>> plantList = {
    'A': [
      'Alderholz / Aquilaria malaccensis',
      'Ajowan - Trachyspermum ammi',
      'Amyris - Amyris balsamifera',
      'Andean Mint - Minthostachys mollis',
      'Angelica - Angelica archangelica',
      'Anise - Pimpinella anisum',
      'Swiss Pine / Zirbelkiefer - Pinus cembra',
      'Atlas Cedar - Cedrus atlantica',
    ],
    'B': [
      'Valerian - Valeriana officinalis',
      'Balsam Fir - Abies balsamea',
      'Basil - Ocimum basilicum',
      'Bay Laurel - Laurus nobilis',
      'Bergamot - Citrus bergamia',
      'Birch - Betula lenta',
      'Black Pepper - Piper nigrum',
      'Blue Tansy - Tanacetum annuum',
    ],
    'C': [
      'Cajeput - Melaleuca cajuputi',
      'Caraway - Carum carvi',
      'Cardamom - Elettaria cardamomum',
      'Carrot Seed - Daucus carota',
      'Catnip - Nepeta cataria',
      'Cedarwood - Juniperus virginiana',
      'Chamomile - Matricaria chamomilla',
      'Cinnamon - Cinnamomum verum',
    ],
    'D': [
      'Dill - Anethum graveolens',
      'Douglas Fir - Pseudotsuga menziesii',
      'Dragonhead - Dracocephalum moldavica',
      'Davana - Artemisia pallens',
      'Damask Rose - Rosa damascena',
      'Dandelion - Taraxacum officinale',
      'Deodar Cedar - Cedrus deodara',
      'Dittany - Origanum dictamnus',
    ],
    'E': [
      'Eucalyptus - Eucalyptus globulus',
      'Elderflower - Sambucus nigra',
      'Elemi - Canarium luzonicum',
      'Evening Primrose - Oenothera biennis',
      'Evergreen - Tsuga canadensis',
      'Estragon - Artemisia dracunculus',
      'Echinacea - Echinacea purpurea',
      'Egyptian Geranium - Pelargonium graveolens',
    ],
    'F': [
      'Fennel - Foeniculum vulgare',
      'Fir Needle - Abies sibirica',
      'Frankincense - Boswellia carterii',
      'French Lavender - Lavandula angustifolia',
      'Feverfew - Tanacetum parthenium',
      'Field Mint - Mentha arvensis',
      'Fragonia - Agonis fragrans',
      'Foxtail Lily - Eremurus robustus',
    ],
    'G': [
      'Galbanum - Ferula galbaniflua',
      'Gardenia - Gardenia jasminoides',
      'Geranium - Pelargonium graveolens',
      'Ginger - Zingiber officinale',
      'Goldenrod - Solidago canadensis',
      'Grapefruit - Citrus paradisi',
      'Guaiacwood - Bulnesia sarmientoi',
      'Gurjun Balsam - Dipterocarpus turbinatus',
    ],
    'H': [
      'Helichrysum - Helichrysum italicum',
      'Hibiscus - Hibiscus sabdariffa',
      'Himalayan Cedar - Cedrus deodara',
      'Hyssop - Hyssopus officinalis',
      'Ho Wood - Cinnamomum camphora',
      'Honey Myrtle - Melaleuca teretifolia',
      'Honeysuckle - Lonicera periclymenum',
      'Hawthorn - Crataegus monogyna',
    ],
    'I': [
      'Immortelle - Helichrysum italicum',
      'Incense Cedar - Calocedrus decurrens',
      'Indian Sandalwood - Santalum album',
      'Iris - Iris pallida',
      'Inula - Inula graveolens',
      'Iceland Moss - Cetraria islandica',
      'Italian Strawflower - Helichrysum italicum',
      'Indigo - Indigofera tinctoria',
    ],
    'J': [
      'Jasmine - Jasminum officinale',
      'Juniper Berry - Juniperus communis',
      'Japanese Mint - Mentha arvensis',
      'Jojoba - Simmondsia chinensis',
      'Jack Pine - Pinus banksiana',
      'Jerusalem Pine - Pinus halepensis',
      'Java Pepper - Piper cubeba',
      'Jonquil - Narcissus jonquilla',
    ],
    'K': [
      'Kaffir Lime - Citrus hystrix',
      'Kanuka - Kunzea ericoides',
      'Kapoor Tulsi - Ocimum sanctum',
      'Kewra - Pandanus odorifer',
      'Kunzea - Kunzea ambigua',
      'Khella - Ammi visnaga',
      'Kiwi Seed - Actinidia chinensis',
      'Knobweed - Hyptis capitata',
    ],
    'L': [
      'Lavender - Lavandula angustifolia',
      'Lemon - Citrus limon',
      'Lemongrass - Cymbopogon citratus',
      'Linden Blossom - Tilia cordata',
      'Litsea - Litsea cubeba',
      'Laurel Leaf - Laurus nobilis',
      'Lemon Balm - Melissa officinalis',
      'Larch - Larix decidua',
    ],
    'M': [
      'Marjoram - Origanum majorana',
      'Myrrh - Commiphora myrrha',
      'Mandarin - Citrus reticulata',
      'Mugwort - Artemisia vulgaris',
      'Myrtle - Myrtus communis',
      'Manuka - Leptospermum scoparium',
      'Melissa - Melissa officinalis',
      'Magnolia - Magnolia grandiflora',
    ],
    'N': [
      'Neroli - Citrus aurantium',
      'Nutmeg - Myristica fragrans',
      'Niaouli - Melaleuca quinquenervia',
      'Norway Spruce - Picea abies',
      'Nasturtium - Tropaeolum majus',
      'Narcissus - Narcissus poeticus',
      'Neem - Azadirachta indica',
      'Noble Fir - Abies procera',
    ],
    'O': [
      'Orange - Citrus sinensis',
      'Oregano - Origanum vulgare',
      'Opoponax - Commiphora guidottii',
      'Osmanthus - Osmanthus fragrans',
      'Oakmoss - Evernia prunastri',
      'Orris Root - Iris germanica',
      'Olive Leaf - Olea europaea',
      'Onion Seed - Nigella sativa',
    ],
    'P': [
      'Patchouli - Pogostemon cablin',
      'Peppermint - Mentha piperita',
      'Pine - Pinus sylvestris',
      'Palmarosa - Cymbopogon martinii',
      'Palo Santo - Bursera graveolens',
      'Petitgrain - Citrus aurantium',
      'Pimento Berry - Pimenta dioica',
      'Pink Pepper - Schinus molle',
    ],
    'Q': [
      'Quince - Cydonia oblonga',
      'Queensland Boronia - Boronia megastigma',
      'Quassia - Quassia amara',
      'Quaking Aspen - Populus tremuloides',
      'Queen of the Night - Selenicereus grandiflorus',
      'Quillaja - Quillaja saponaria',
      'Queensland Frangipani - Hymenosporum flavum',
      'Quamash - Camassia quamash',
    ],
    'R': [
      'Rose - Rosa centifolia',
      'Rosemary - Rosmarinus officinalis',
      'Rosewood - Aniba rosaeodora',
      'Ravintsara - Cinnamomum camphora',
      'Red Cedar - Juniperus virginiana',
      'Rhododendron - Rhododendron ferrugineum',
      'Roman Chamomile - Chamaemelum nobile',
      'Rockrose - Cistus ladanifer',
    ],
    'S': [
      'Sandalwood - Santalum album',
      'Sage - Salvia officinalis',
      'Spearmint - Mentha spicata',
      'Spruce - Picea mariana',
      'Star Anise - Illicium verum',
      'Saffron - Crocus sativus',
      'Siam Wood - Fokienia hodginsii',
      'Sweet Marjoram - Origanum majorana',
    ],
    'T': [
      'Tea Tree - Melaleuca alternifolia',
      'Thyme - Thymus vulgaris',
      'Tangerine - Citrus tangerina',
      'Tuberose - Polianthes tuberosa',
      'Turmeric - Curcuma longa',
      'Tagetes - Tagetes minuta',
      'Tarragon - Artemisia dracunculus',
      'Tonka Bean - Dipteryx odorata',
    ],
    'U': [
      'Umbrella Pine - Pinus pinea',
      'Uva Ursi - Arctostaphylos uva-ursi',
      'Usnea - Usnea barbata',
      'Upland Cotton - Gossypium hirsutum',
      'Unicorn Root - Aletris farinosa',
      'Ugni - Ugni molinae',
      'Ulex - Ulex europaeus',
      'Upright Hedge Parsley - Torilis japonica',
    ],
    'V': [
      'Vanilla - Vanilla planifolia',
      'Vetiver - Vetiveria zizanioides',
      'Violet - Viola odorata',
      'Virginia Cedarwood - Juniperus virginiana',
      'Valerian - Valeriana officinalis',
      'Verbena - Aloysia citrodora',
      'Vervain - Verbena officinalis',
      'Vine - Vitis vinifera',
    ],
    'W': [
      'Wintergreen - Gaultheria procumbens',
      'White Pine - Pinus strobus',
      'Wild Orange - Citrus sinensis',
      'Willow - Salix alba',
      'Wormwood - Artemisia absinthium',
      'Wattle - Acacia decurrens',
      'White Sage - Salvia apiana',
      'Walnut - Juglans regia',
    ],
    'X': [
      'Xanthoxylum - Zanthoxylum americanum',
      'Xerophyllum - Xerophyllum tenax',
      'Ximenia - Ximenia americana',
      'Xylopia - Xylopia aethiopica',
      'Xyris - Xyris difformis',
      'Xanthium - Xanthium strumarium',
      'Xerochrysum - Xerochrysum bracteatum',
      'Xanthoceras - Xanthoceras sorbifolium',
    ],
    'Y': [
      'Ylang Ylang - Cananga odorata',
      'Yarrow - Achillea millefolium',
      'Yellow Pine - Pinus ponderosa',
      'Yuzu - Citrus junos',
      'Yellow Dock - Rumex crispus',
      'Yerba Mate - Ilex paraguariensis',
      'Yellow Flag - Iris pseudacorus',
      'Yew - Taxus baccata',
    ],
    'Z': [
      'Zdravetz - Geranium macrorrhizum',
      'Zedoary - Curcuma zedoaria',
      'Ziziphus - Ziziphus jujuba',
      'Zanthoxylum - Zanthoxylum piperitum',
      'Zinnia - Zinnia elegans',
      'Zeb草 - Zea mays',
      'Zygopetalum - Zygopetalum maculatum',
      'Ziziphora - Ziziphora clinopodioides',
    ],
  };
}