class PlantData {
  static const Map<String, List<String>> plantList = {
    'A': [
      'Alderholz / Aquilaria malaccensis',
      'Ajowan - Trachyspermum ammi',
      'Amyris - Amyris balsamifera',
      'Andean Mint - Minthostachys mollis',
      'Angelica - Angelica archangelica',
      'Anise - Pimpinella anisum',
      'Swiss Pine / Zirbelkiefer - Pinus cembra',
      'Atlas Cedar - Cedrus atlantica',
    ],
    'B': [
      'Valerian - Valeriana officinalis',
      'Balsam Fir - Abies balsamea',
      'Basil - Ocimum basilicum',
      'Bay Laurel - Laurus nobilis',
      'Bergamot - Citrus bergamia',
      'Birch - Betula lenta',
      'Black Pepper - Piper nigrum',
      'Blue Tansy - Tanacetum annuum',
    ],
    'C': [
      'Cajeput - Melaleuca cajuputi',
      'Caraway - Carum carvi',
      'Cardamom - Elettaria cardamomum',
      'Carrot Seed - Daucus carota',
      'Catnip - Nepeta cataria',
      'Cedarwood - Juniperus virginiana',
      'Chamomile - Matricaria chamomilla',
      'Cinnamon - Cinnamomum verum',
    ],
    'D': [
      'Dill - Anethum graveolens',
      'Douglas Fir - Pseudotsuga menziesii',
      'Dragonhead - Dracocephalum moldavica',
      'Davana - Artemisia pallens',
      'Damask Rose - Rosa damascena',
      'Dandelion - Taraxacum officinale',
      'Deodar Cedar - Cedrus deodara',
      'Dittany - Origanum dictamnus',
    ],
    'E': [
      'Eucalyptus - Eucalyptus globulus',
      'Elderflower - Sambucus nigra',
      'Elemi - Canarium luzonicum',
      'Evening Primrose - Oenothera biennis',
      'Evergreen - Tsuga canadensis',
      'Estragon - Artemisia dracunculus',
      'Echinacea - Echinacea purpurea',
      'Egyptian Geranium - Pelargonium graveolens',
    ],
    'F': [
      'Fennel - Foeniculum vulgare',
      'Fir Needle - Abies sibirica',
      'Frankincense - Boswellia carterii',
      'French Lavender - Lavandula angustifolia',
      'Feverfew - Tanacetum parthenium',
      'Field Mint - Mentha arvensis',
      'Fragonia - Agonis fragrans',
      'Foxtail Lily - Eremurus robustus',
    ],
    'G': [
      'Galbanum - Ferula galbaniflua',
      'Gardenia - Gardenia jasminoides',
      'Geranium - Pelargonium graveolens',
      'Ginger - Zingiber officinale',
      'Goldenrod - Solidago canadensis',
      'Grapefruit - Citrus paradisi',
      'Guaiacwood - Bulnesia sarmientoi',
      'Gurjun Balsam - Dipterocarpus turbinatus',
    ],
    'H': [
      'Helichrysum - Helichrysum italicum',
      'Hibiscus - Hibiscus sabdariffa',
      'Himalayan Cedar - Cedrus deodara',
      'Hyssop - Hyssopus officinalis',
      'Ho Wood - Cinnamomum camphora',
      'Honey Myrtle - Melaleuca teretifolia',
      'Honeysuckle - Lonicera periclymenum',
      'Hawthorn - Crataegus monogyna',
    ],
    'I': [
      'Immortelle - Helichrysum italicum',
      'Incense Cedar - Calocedrus decurrens',
      'Indian Sandalwood - Santalum album',
      'Iris - Iris pallida',
      'Inula - Inula graveolens',
      'Iceland Moss - Cetraria islandica',
      'Italian Strawflower - Helichrysum italicum',
      'Indigo - Indigofera tinctoria',
    ],
    'J': [
      'Jasmine - Jasminum officinale',
      'Juniper Berry - Juniperus communis',
      'Japanese Mint - Mentha arvensis',
      'Jojoba - Simmondsia chinensis',
      'Jack Pine - Pinus banksiana',
      'Jerusalem Pine - Pinus halepensis',
      'Java Pepper - Piper cubeba',
      'Jonquil - Narcissus jonquilla',
    ],
    'K': [
      'Kaffir Lime - Citrus hystrix',
      'Kanuka - Kunzea ericoides',
      'Kapoor Tulsi - Ocimum sanctum',
      'Kewra - Pandanus odorifer',
      'Kunzea - Kunzea ambigua',
      'Khella - Ammi visnaga',
      'Kiwi Seed - Actinidia chinensis',
      'Knobweed - Hyptis capitata',
    ],
    'L': [
      'Lavender - Lavandula angustifolia',
      'Lemon - Citrus limon',
      'Lemongrass - Cymbopogon citratus',
      'Linden Blossom - Tilia cordata',
      'Litsea - Litsea cubeba',
      'Laurel Leaf - Laurus nobilis',
      'Lemon Balm - Melissa officinalis',
      'Larch - Larix decidua',
    ],
    'M': [
      'Marjoram - Origanum majorana',
      'Myrrh - Commiphora myrrha',
      'Mandarin - Citrus reticulata',
      'Mugwort - Artemisia vulgaris',
      'Myrtle - Myrtus communis',
      'Manuka - Leptospermum scoparium',
      'Melissa - Melissa officinalis',
      'Magnolia - Magnolia grandiflora',
    ],
    'N': [
      'Neroli - Citrus aurantium',
      'Nutmeg - Myristica fragrans',
      'Niaouli - Melaleuca quinquenervia',
      'Norway Spruce - Picea abies',
      'Nasturtium - Tropaeolum majus',
      'Narcissus - Narcissus poeticus',
      'Neem - Azadirachta indica',
      'Noble Fir - Abies procera',
    ],
    'O': [
      'Orange - Citrus sinensis',
      'Oregano - Origanum vulgare',
      'Opoponax - Commiphora guidottii',
      'Osmanthus - Osmanthus fragrans',
      'Oakmoss - Evernia prunastri',
      'Orris Root - Iris germanica',
      'Olive Leaf - Olea europaea',
      'Onion Seed - Nigella sativa',
    ],
    'P': [
      'Patchouli - Pogostemon cablin',
      'Peppermint - Mentha piperita',
      'Pine - Pinus sylvestris',
      'Palmarosa - Cymbopogon martinii',
      'Palo Santo - Bursera graveolens',
      'Petitgrain - Citrus aurantium',
      'Pimento Berry - Pimenta dioica',
      'Pink Pepper - Schinus molle',
    ],
    'Q': [
      'Quince - Cydonia oblonga',
      'Queensland Boronia - Boronia megastigma',
      'Quassia - Quassia amara',
      'Quaking Aspen - Populus tremuloides',
      'Queen of the Night - Selenicereus grandiflorus',
      'Quillaja - Quillaja saponaria',
      'Queensland Frangipani - Hymenosporum flavum',
      'Quamash - Camassia quamash',
    ],
    'R': [
      'Rose - Rosa centifolia',
      'Rosemary - Rosmarinus officinalis',
      'Rosewood - Aniba rosaeodora',
      'Ravintsara - Cinnamomum camphora',
      'Red Cedar - Juniperus virginiana',
      'Rhododendron - Rhododendron ferrugineum',
      'Roman Chamomile - Chamaemelum nobile',
      'Rockrose - Cistus ladanifer',
    ],
    'S': [
      'Sandalwood - Santalum album',
      'Sage - Salvia officinalis',
      'Spearmint - Mentha spicata',
      'Spruce - Picea mariana',
      'Star Anise - Illicium verum',
      'Saffron - Crocus sativus',
      'Siam Wood - Fokienia hodginsii',
      'Sweet Marjoram - Origanum majorana',
    ],
    'T': [
      'Tea Tree - Melaleuca alternifolia',
      'Thyme - Thymus vulgaris',
      'Tangerine - Citrus tangerina',
      'Tuberose - Polianthes tuberosa',
      'Turmeric - Curcuma longa',
      'Tagetes - Tagetes minuta',
      'Tarragon - Artemisia dracunculus',
      'Tonka Bean - Dipteryx odorata',
    ],
    'U': [
      'Umbrella Pine - Pinus pinea',
      'Uva Ursi - Arctostaphylos uva-ursi',
      'Usnea - Usnea barbata',
      'Upland Cotton - Gossypium hirsutum',
      'Unicorn Root - Aletris farinosa',
      'Ugni - Ugni molinae',
      'Ulex - Ulex europaeus',
      'Upright Hedge Parsley - Torilis japonica',
    ],
    'V': [
      'Vanilla - Vanilla planifolia',
      'Vetiver - Vetiveria zizanioides',
      'Violet - Viola odorata',
      'Virginia Cedarwood - Juniperus virginiana',
      'Valerian - Valeriana officinalis',
      'Verbena - Aloysia citrodora',
      'Vervain - Verbena officinalis',
      'Vine - Vitis vinifera',
    ],
    'W': [
      'Wintergreen - Gaultheria procumbens',
      'White Pine - Pinus strobus',
      'Wild Orange - Citrus sinensis',
      'Willow - Salix alba',
      'Wormwood - Artemisia absinthium',
      'Wattle - Acacia decurrens',
      'White Sage - Salvia apiana',
      'Walnut - Juglans regia',
    ],
    'X': [
      'Xanthoxylum - Zanthoxylum americanum',
      'Xerophyllum - Xerophyllum tenax',
      'Ximenia - Ximenia americana',
      'Xylopia - Xylopia aethiopica',
      'Xyris - Xyris difformis',
      'Xanthium - Xanthium strumarium',
      'Xerochrysum - Xerochrysum bracteatum',
      'Xanthoceras - Xanthoceras sorbifolium',
    ],
    'Y': [
      'Ylang Ylang - Cananga odorata',
      'Yarrow - Achillea millefolium',
      'Yellow Pine - Pinus ponderosa',
      'Yuzu - Citrus junos',
      'Yellow Dock - Rumex crispus',
      'Yerba Mate - Ilex paraguariensis',
      'Yellow Flag - Iris pseudacorus',
      'Yew - Taxus baccata',
    ],
    'Z': [
      'Zdravetz - Geranium macrorrhizum',
      'Zedoary - Curcuma zedoaria',
      'Ziziphus - Ziziphus jujuba',
      'Zanthoxylum - Zanthoxylum piperitum',
      'Zinnia - Zinnia elegans',
      'Zeb草 - Zea mays',
      'Zygopetalum - Zygopetalum maculatum',
      'Ziziphora - Ziziphora clinopodioides',
    ],
  };  static const Map<String, List<String>> essentialOils = {
    'A': [
      'Argan Oil - Argania spinosa',
      'Almond Sweet Oil - Prunus amygdalus',
      'Apricot Kernel Oil - Prunus armeniaca',
      'Avocado Oil - Persea americana',
      'Angelica Seed Oil - Angelica archangelica',
      'Anise Oil - Pimpinella anisum',
      'Atlas Cedar Oil - Cedrus atlantica',
      'Amyris Oil - Amyris balsamifera',
    ],
    'B': [
      'Bergamot Oil - Citrus bergamia',
      'Black Pepper Oil - Piper nigrum',
      'Basil Oil - Ocimum basilicum',
      'Bay Laurel Oil - Laurus nobilis',
      'Birch Oil - Betula lenta',
      'Blue Tansy Oil - Tanacetum annuum',
      'Benzoin Oil - Styrax benzoin',
      'Borage Seed Oil - Borago officinalis',
    ],
    'C': [
      'Coconut Oil - Cocos nucifera',
      'Carrot Seed Oil - Daucus carota',
      'Chamomile Oil - Matricaria chamomilla',
      'Cedarwood Oil - Juniperus virginiana',
      'Cinnamon Oil - Cinnamomum verum',
      'Clary Sage Oil - Salvia sclarea',
      'Cypress Oil - Cupressus sempervirens',
      'Citronella Oil - Cymbopogon nardus',
    ],
    'D': [
      'Dill Oil - Anethum graveolens',
      'Douglas Fir Oil - Pseudotsuga menziesii',
      'Damask Rose Oil - Rosa damascena',
      'Davana Oil - Artemisia pallens',
      'Dragon Blood Oil - Dracaena draco',
      'Deodar Cedar Oil - Cedrus deodara',
      'Dandelion Oil - Taraxacum officinale',
      'Diesel Oil - Pinus sylvestris',
    ],
    'E': [
      'Eucalyptus Oil - Eucalyptus globulus',
      'Evening Primrose Oil - Oenothera biennis',
      'Elemi Oil - Canarium luzonicum',
      'Echinacea Oil - Echinacea purpurea',
      'Egyptian Geranium Oil - Pelargonium graveolens',
      'Elderflower Oil - Sambucus nigra',
      'Estragon Oil - Artemisia dracunculus',
      'Eucalyptus Lemon Oil - Eucalyptus citriodora',
    ],
    'F': [
      'Frankincense Oil - Boswellia carterii',
      'Fennel Oil - Foeniculum vulgare',
      'Fir Needle Oil - Abies sibirica',
      'French Lavender Oil - Lavandula angustifolia',
      'Fragonia Oil - Agonis fragrans',
      'Feverfew Oil - Tanacetum parthenium',
      'Field Mint Oil - Mentha arvensis',
      'Fenugreek Oil - Trigonella foenum-graecum',
    ],
    'G': [
      'Geranium Oil - Pelargonium graveolens',
      'Ginger Oil - Zingiber officinale',
      'Grapefruit Oil - Citrus paradisi',
      'Grapeseed Oil - Vitis vinifera',
      'Goldenrod Oil - Solidago canadensis',
      'Guaiacwood Oil - Bulnesia sarmientoi',
      'Galbanum Oil - Ferula galbaniflua',
      'German Chamomile Oil - Matricaria recutita',
    ],
    'H': [
      'Helichrysum Oil - Helichrysum italicum',
      'Hazelnut Oil - Corylus avellana',
      'Hemp Seed Oil - Cannabis sativa',
      'Hyssop Oil - Hyssopus officinalis',
      'Ho Wood Oil - Cinnamomum camphora',
      'Honey Myrtle Oil - Melaleuca teretifolia',
      'Himalayan Cedar Oil - Cedrus deodara',
      'Hibiscus Oil - Hibiscus sabdariffa',
    ],
    'I': [
      'Immortelle Oil - Helichrysum italicum',
      'Indian Sandalwood Oil - Santalum album',
      'Iris Oil - Iris pallida',
      'Inula Oil - Inula graveolens',
      'Incense Cedar Oil - Calocedrus decurrens',
      'Iceland Moss Oil - Cetraria islandica',
      'Indigo Oil - Indigofera tinctoria',
      'Italian Strawflower Oil - Helichrysum italicum',
    ],
    'J': [
      'Jasmine Oil - Jasminum officinale',
      'Jojoba Oil - Simmondsia chinensis',
      'Juniper Berry Oil - Juniperus communis',
      'Japanese Mint Oil - Mentha arvensis',
      'Jack Pine Oil - Pinus banksiana',
      'Java Pepper Oil - Piper cubeba',
      'Jonquil Oil - Narcissus jonquilla',
      'Jerusalem Pine Oil - Pinus halepensis',
    ],
    'K': [
      'Kaffir Lime Oil - Citrus hystrix',
      'Kanuka Oil - Kunzea ericoides',
      'Kapoor Tulsi Oil - Ocimum sanctum',
      'Kewra Oil - Pandanus odorifer',
      'Kunzea Oil - Kunzea ambigua',
      'Khella Oil - Ammi visnaga',
      'Kiwi Seed Oil - Actinidia chinensis',
      'Knobweed Oil - Hyptis capitata',
    ],
    'L': [
      'Lavender Oil - Lavandula angustifolia',
      'Lemon Oil - Citrus limon',
      'Lemongrass Oil - Cymbopogon citratus',
      'Lime Oil - Citrus aurantifolia',
      'Litsea Oil - Litsea cubeba',
      'Lemon Balm Oil - Melissa officinalis',
      'Laurel Leaf Oil - Laurus nobilis',
      'Larch Oil - Larix decidua',
    ],
    'M': [
      'Marula Oil - Sclerocarya birrea',
      'Myrrh Oil - Commiphora myrrha',
      'Marjoram Oil - Origanum majorana',
      'Mandarin Oil - Citrus reticulata',
      'Manuka Oil - Leptospermum scoparium',
      'Myrtle Oil - Myrtus communis',
      'Melissa Oil - Melissa officinalis',
      'Magnolia Oil - Magnolia grandiflora',
    ],
    'N': [
      'Neroli Oil - Citrus aurantium',
      'Nutmeg Oil - Myristica fragrans',
      'Niaouli Oil - Melaleuca quinquenervia',
      'Norway Spruce Oil - Picea abies',
      'Neem Oil - Azadirachta indica',
      'Narcissus Oil - Narcissus poeticus',
      'Noble Fir Oil - Abies procera',
      'Nasturtium Oil - Tropaeolum majus',
    ],
    'O': [
      'Orange Oil - Citrus sinensis',
      'Oregano Oil - Origanum vulgare',
      'Opoponax Oil - Commiphora guidottii',
      'Osmanthus Oil - Osmanthus fragrans',
      'Oakmoss Oil - Evernia prunastri',
      'Orris Root Oil - Iris germanica',
      'Olive Oil - Olea europaea',
      'Onion Seed Oil - Nigella sativa',
    ],
    'P': [
      'Patchouli Oil - Pogostemon cablin',
      'Peppermint Oil - Mentha piperita',
      'Pine Oil - Pinus sylvestris',
      'Palmarosa Oil - Cymbopogon martinii',
      'Palo Santo Oil - Bursera graveolens',
      'Petitgrain Oil - Citrus aurantium',
      'Pink Pepper Oil - Schinus molle',
      'Pomegranate Seed Oil - Punica granatum',
    ],
    'Q': [
      'Quince Oil - Cydonia oblonga',
      'Queensland Boronia Oil - Boronia megastigma',
      'Quassia Oil - Quassia amara',
      'Queen of the Night Oil - Selenicereus grandiflorus',
      'Quillaja Oil - Quillaja saponaria',
      'Queensland Frangipani Oil - Hymenosporum flavum',
      'Quamash Oil - Camassia quamash',
      'Quebracho Oil - Schinopsis lorentzii',
    ],
    'R': [
      'Rose Oil - Rosa centifolia',
      'Rosehip Oil - Rosa canina',
      'Rosemary Oil - Rosmarinus officinalis',
      'Rosewood Oil - Aniba rosaeodora',
      'Ravintsara Oil - Cinnamomum camphora',
      'Roman Chamomile Oil - Chamaemelum nobile',
      'Rockrose Oil - Cistus ladanifer',
      'Red Cedar Oil - Juniperus virginiana',
    ],
    'S': [
      'Sandalwood Oil - Santalum album',
      'Squalane Oil - Squalus acanthias',
      'Sage Oil - Salvia officinalis',
      'Spearmint Oil - Mentha spicata',
      'Spruce Oil - Picea mariana',
      'Star Anise Oil - Illicium verum',
      'Sweet Almond Oil - Prunus amygdalus',
      'Sunflower Oil - Helianthus annuus',
    ],
    'T': [
      'Tea Tree Oil - Melaleuca alternifolia',
      'Thyme Oil - Thymus vulgaris',
      'Tangerine Oil - Citrus tangerina',
      'Tuberose Oil - Polianthes tuberosa',
      'Turmeric Oil - Curcuma longa',
      'Tagetes Oil - Tagetes minuta',
      'Tarragon Oil - Artemisia dracunculus',
      'Tonka Bean Oil - Dipteryx odorata',
    ],
    'U': [
      'Umbrella Pine Oil - Pinus pinea',
      'Uva Ursi Oil - Arctostaphylos uva-ursi',
      'Usnea Oil - Usnea barbata',
      'Unicorn Root Oil - Aletris farinosa',
      'Ugni Oil - Ugni molinae',
      'Ulex Oil - Ulex europaeus',
      'Upland Cotton Oil - Gossypium hirsutum',
      'Urtica Oil - Urtica dioica',
    ],
    'V': [
      'Vitamin E Oil - Tocopherol',
      'Vanilla Oil - Vanilla planifolia',
      'Vetiver Oil - Vetiveria zizanioides',
      'Violet Oil - Viola odorata',
      'Virginia Cedarwood Oil - Juniperus virginiana',
      'Valerian Oil - Valeriana officinalis',
      'Verbena Oil - Aloysia citrodora',
      'Vine Oil - Vitis vinifera',
    ],
    'W': [
      'Wintergreen Oil - Gaultheria procumbens',
      'White Pine Oil - Pinus strobus',
      'Wild Orange Oil - Citrus sinensis',
      'Willow Oil - Salix alba',
      'Wormwood Oil - Artemisia absinthium',
      'White Sage Oil - Salvia apiana',
      'Walnut Oil - Juglans regia',
      'Wheat Germ Oil - Triticum vulgare',
    ],
    'X': [
      'Xanthoxylum Oil - Zanthoxylum americanum',
      'Xerophyllum Oil - Xerophyllum tenax',
      'Ximenia Oil - Ximenia americana',
      'Xylopia Oil - Xylopia aethiopica',
      'Xanthium Oil - Xanthium strumarium',
      'Xerochrysum Oil - Xerochrysum bracteatum',
      'Xanthoceras Oil - Xanthoceras sorbifolium',
      'Xyris Oil - Xyris difformis',
    ],
    'Y': [
      'Ylang Ylang Oil - Cananga odorata',
      'Yarrow Oil - Achillea millefolium',
      'Yellow Pine Oil - Pinus ponderosa',
      'Yuzu Oil - Citrus junos',
      'Yellow Dock Oil - Rumex crispus',
      'Yerba Mate Oil - Ilex paraguariensis',
      'Yellow Flag Oil - Iris pseudacorus',
      'Yew Oil - Taxus baccata',
    ],
    'Z': [
      'Zdravetz Oil - Geranium macrorrhizum',
      'Zedoary Oil - Curcuma zedoaria',
      'Ziziphus Oil - Ziziphus jujuba',
      'Zanthoxylum Oil - Zanthoxylum piperitum',
      'Zinnia Oil - Zinnia elegans',
      'Ziziphora Oil - Ziziphora clinopodioides',
      'Zebrawood Oil - Microberlinia brazzavillensis',
      'Zest Oil Blend - Citrus Mixed',
    ],
  };

  static const Map<String, List<String>> recipes = {
    'A': [
      'Anti-Aging Face Serum',
      'Acne Spot Treatment',
      'Argan Hair Mask',
      'Aloe Vera Moisturizer',
      'Aromatherapy Bath Salts',
      'Avocado Face Mask',
      'Apple Cider Vinegar Toner',
      'Antioxidant Eye Cream',
    ],
    'B': [
      'Brightening Vitamin C Serum',
      'Body Butter Recipe',
      'Blemish Control Oil',
      'Bath Bomb Recipe',
      'Blackhead Removal Mask',
      'Beauty Sleep Oil Blend',
      'Botanical Face Cleanser',
      'Bronzing Body Oil',
    ],
    'C': [
      'Coconut Oil Hair Treatment',
      'Cellulite Reduction Cream',
      'Cleansing Oil Recipe',
      'Collagen Boosting Mask',
      'Cuticle Care Oil',
      'Calming Chamomile Toner',
      'Coffee Body Scrub',
      'Cucumber Eye Pads',
    ],
    'D': [
      'Dark Circle Reducer',
      'Deep Cleansing Clay Mask',
      'Dry Skin Relief Balm',
      'Detox Face Mask',
      'Daily Moisturizing Cream',
      'Dandruff Treatment Oil',
      'Deodorant Recipe',
      'Damaged Hair Repair Serum',
    ],
    'E': [
      'Exfoliating Sugar Scrub',
      'Eye Wrinkle Cream',
      'Essential Oil Perfume',
      'Energizing Body Wash',
      'Evening Skincare Routine',
      'Eczema Relief Balm',
      'Elasticity Boosting Serum',
      'Eyebrow Growth Oil',
    ],
    'F': [
      'Firming Face Mask',
      'Foot Care Cream',
      'Face Brightening Serum',
      'Frizz Control Hair Oil',
      'Fresh Breath Spray',
      'Foundation Primer Recipe',
      'Facial Steam Blend',
      'Fragrant Body Mist',
    ],
    'G': [
      'Gentle Baby Oil',
      'Glow Boosting Face Oil',
      'Green Tea Face Mask',
      'Growth Stimulating Hair Oil',
      'Glycolic Acid Peel',
      'Grape Seed Anti-Aging Oil',
      'Golden Turmeric Mask',
      'Geranium Rose Toner',
    ],
    'H': [
      'Hydrating Face Serum',
      'Hair Growth Treatment',
      'Hand Cream Recipe',
      'Healing Lip Balm',
      'Honey Oat Face Mask',
      'Hot Oil Hair Treatment',
      'Hyperpigmentation Serum',
      'Herbal Facial Steam',
    ],
    'I': [
      'Illuminating Face Oil',
      'Intensive Repair Cream',
      'Iron-Rich Hair Mask',
      'Instant Glow Face Pack',
      'Ingrown Hair Treatment',
      'Immortelle Anti-Aging Serum',
      'Iris Brightening Cream',
      'Invigorating Body Scrub',
    ],
    'J': [
      'Jasmine Night Cream',
      'Jojoba Cleansing Oil',
      'Jade Roller Face Oil',
      'Joint Pain Relief Balm',
      'Juniper Detox Oil',
      'Japanese Rice Water Toner',
      'Jelly Face Mask',
      'Jawline Firming Serum',
    ],
    'K': [
      'Keratin Hair Treatment',
      'Kojic Acid Brightening Serum',
      'Kiwi Vitamin C Mask',
      'Knee Softening Cream',
      'Kelp Detox Body Wrap',
      'Kukui Nut Hair Oil',
      'Kaolin Clay Face Mask',
      'Kaffir Lime Body Scrub',
    ],
    'L': [
      'Lavender Sleep Spray',
      'Lip Plumping Gloss',
      'Lemon Brightening Mask',
      'Lash Growth Serum',
      'Lightening Body Oil',
      'Luxurious Face Cream',
      'Leave-In Hair Conditioner',
      'Lymphatic Drainage Oil',
    ],
    'M': [
      'Moisturizing Body Lotion',
      'Marula Oil Face Serum',
      'Makeup Remover Oil',
      'Muscle Relief Balm',
      'Matcha Face Mask',
      'Microdermabrasion Scrub',
      'Matte Lip Balm',
      'Memory Enhancement Oil',
    ],
    'N': [
      'Nourishing Hair Mask',
      'Night Repair Serum',
      'Natural Deodorant',
      'Neck Firming Cream',
      'Nail Strengthening Oil',
      'Neroli Hydrating Mist',
      'Niacinamide Pore Minimizer',
      'Neem Acne Treatment',
    ],
    'O': [
      'Oil Cleansing Method',
      'Oatmeal Gentle Scrub',
      'Orange Peel Body Scrub',
      'Overnight Hair Treatment',
      'Oily Skin Control Serum',
      'Organic Face Moisturizer',
      'Oxygen Infusion Mask',
      'Ombre Lip Balm',
    ],
    'P': [
      'Pore Minimizing Toner',
      'Peppermint Foot Cream',
      'Peptide Anti-Aging Cream',
      'Purifying Charcoal Mask',
      'Pomegranate Face Serum',
      'Professional Hair Oil',
      'Pigmentation Corrector',
      'Plumping Lip Treatment',
    ],
    'Q': [
      'Quick Glow Face Mask',
      'Quinoa Protein Hair Mask',
      'Queen Bee Face Cream',
      'Quench Hydrating Serum',
      'Quiet Mind Aromatherapy Oil',
      'Quality Sleep Pillow Spray',
      'Quartz Crystal Face Oil',
      'Quick Dry Nail Oil',
    ],
    'R': [
      'Retinol Night Serum',
      'Rose Water Toner',
      'Repair Hair Treatment',
      'Radiance Boosting Mask',
      'Roseberry Lip Balm',
      'Rejuvenating Eye Cream',
      'Rice Bran Exfoliator',
      'Relaxing Bath Oil',
    ],
    'S': [
      'Squalane Hydrating Serum',
      'Stretch Mark Prevention Oil',
      'Scalp Treatment Oil',
      'Sunscreen Face Cream',
      'Soothing After-Sun Gel',
      'Shine Control Face Mist',
      'Sensitive Skin Cleanser',
      'Strengthening Nail Treatment',
    ],
    'T': [
      'Tea Tree Spot Treatment',
      'Tightening Face Mask',
      'Turmeric Brightening Paste',
      'Tinted Moisturizer Recipe',
      'Thickening Hair Serum',
      'Toning Body Oil',
      'Tender Eye Cream',
      'Timeless Beauty Elixir',
    ],
    'U': [
      'Under Eye Brightening Cream',
      'Ultra Hydrating Face Mask',
      'Uplifting Aromatherapy Blend',
      'UV Protection Face Oil',
      'Unscented Baby Lotion',
      'Ultimate Hair Repair Mask',
      'Underarm Whitening Cream',
      'Universal Face Cleanser',
    ],
    'V': [
      'Vitamin E Healing Balm',
      'Volume Boosting Hair Mist',
      'Velvet Skin Body Butter',
      'Vanishing Cream Recipe',
      'Violet Soothing Gel',
      'Vegan Lip Balm',
      'Varicose Vein Treatment Oil',
      'Vivid Color Lip Stain',
    ],
    'W': [
      'Wrinkle Fighting Serum',
      'Whitening Face Mask',
      'Waterproof Mascara Recipe',
      'Warming Massage Oil',
      'Weekly Hair Treatment',
      'Wonder Healing Balm',
      'Wax-Free Hair Pomade',
      'Winter Skin Protection Cream',
    ],
    'X': [
      'Xtreme Repair Hair Mask',
      'Xerosis Skin Treatment',
      'Xanthine Caffeine Eye Gel',
      'Xylem Strengthening Serum',
      'Xylitol Lip Balm',
      'Xerophyte Moisture Cream',
      'Xanthophyll Eye Cream',
      'Xenial Calming Oil',
    ],
    'Y': [
      'Youth Restoring Serum',
      'Ylang Ylang Body Oil',
      'Youthful Glow Face Mask',
      'Yarrow Healing Balm',
      'Yellow Clay Detox Mask',
      'Yoga Mat Cleansing Spray',
      'Yeast Extract Hair Treatment',
      'Yummy Lip Scrub',
    ],
    'Z': [
      'Zinc Oxide Sunscreen',
      'Zesty Citrus Body Scrub',
      'Zen Aromatherapy Blend',
      'Zero Waste Shampoo Bar',
      'Zircon Brightening Serum',
      'Zesty Orange Face Mask',
      'Zeal Energy Body Oil',
      'Zone Control Acne Treatment',
    ],
  };
}